language: python
python:
- '2.7'
install: pip install -r requirements-dev.txt --upgrade
script: python -m pytest
deploy:
  provider: pypi
  user: foundryai
  password:
    secure: u+A+KR/PY+0UYDGOKcpKV+TcdoyXDBSWrtD9ahd0eMHODIt/8ky34BJDa7Ovh3NOopF4ypJkXOjJJXliRvJ9jtowIhCu5XqMtvsq18Zhv5igoDHd7FySUCLEMEupKMdWjhPCeMfJkssTUT9EFjEfFDGTH/zmUcZB/eOoGwHZ0bwSC6uTQYR9mkjRpy2cSX2+YI+0z1FXrBC0PVr+euh/9lkXTcM7iOpH78X4g7kO8JyM20Gkn5L6wkn7Iy/T2/p8v4pjLPRpnr24U3+FVFs2ldwGMJEXsCJBs31YWNViAQVKOwrWuGXEGCAuIsQdzrOM3cI44p5SfimSzTP27IbCqvbCV+S6ebNGzqeLZEG4MO0pLtbGn+6GANl7nD+ZCw7fAiEZ8RPXnzwZ5Ikre+Il0YVrV86Y5wL0comZhjUV4FQPe4qooAVwZP96zM+b3qd+hZnMLA8tK4QztcjhRkuYLiDUOP90grY7j0rfyl7cfAvDQgkWNUD0foqgnL335kxCeBTZGfKdGRGbv6zOpV7NL2KyMg45rcI/tQeYRolvkNBe6vjvjbtyGurvoschtCkuQyZiziBObTKZjsdm7njYXig1uzslJiOBJZTKRbFAWDa+2kVuEMmRqlRzmaywQAVO7IhFCOxuyb5xjFKJ+fw6N0IsWNGFOR38bcCT8urLPrU=
  on:
    tags: true
