language: python
python:
- '2.7'
install: pip install -r requirements-dev.txt --upgrade
script: python -m pytest
deploy:
  provider: pypi
  user: foundryai
  password:
    secure: iH5ZZtw//5E+bIet7sdUKHr4fHuwVYTNhvxNIatHMgjlTuDm2yfb20WuJG8wxdeTwsoJtv6OfeBHitVARhc67rucUdYo0nunMIsFQKa2+dtq7TrmU168gPnJOsRO72MULHTlzdUruZutSHncK32hrZYs8e/2un4BdSe1QejENAt4Uvgmhh35gD2hgpwlLQ8KqxFFzoih4gdVruEKt+nEnZtdkslsjgvcPdm/ClcwKuK/7Fqp8/rDMHB5/DSbXxdzKUCJnLI+83RhWxMFwhf6K3bMuwY+2TeCVGtNZFKl9ZL+0430rXWowG1ZuxOKwX3TUWkwMH/JTbakwNWktKJn6lNNwVLCRPfOlQETgYktFkdPVeFTVkTcH4U36Mwd7s6giwQhkohf3gEElT5AgBN42N/C3uMQWK9kYoNksivcgRA+3dsr5c85ABVScG3AtJ7QUEfl1Z13X1Bp1ntBJIdceS2T+UVD3WclfkBUfayfneGUCH3J/iZ/ff5lTttR3xzKsRHr87upEKe6K2/GA2pe72qtb40gdJywSCngkIcf8YZDhb+n+bOINxYPxgEk5AJoxb+2+xbKGJN04DPs9r/BDTN7x3G3JENUpx8ZR5zXtwxqwVjK3Xw/occtaT9QV36GepVi1SZW2NL3c7LQ65uKQp8KwsKtE2r2OZ1g6TQn4Oo=
  on:
    tags: true
