language: python
python:
- '2.7'
install: pip install -r requirements-dev.txt --upgrade
script: python -m pytest
deploy:
  provider: pypi
  user: foundryai
  password:
    secure: Xz7khwbGvZfdl+T/vD83pi3uND4+0wLwBfcXZ5V5Clxx+4ptKy+hOY8U1A92xIsH4tBCxz+Ofb4dphxqMl7gKxPMncztu9AkP/YRQ8hV0d4EfxGHtFU5FRi3jtbaNSOVBxTDUaGgPSrRYbgP8GouJws/eZSaL0Xb+b4tO0ezMMwpRhEXdfcTEWlMuS4fbdZkuSAbQV9kLjL40wgf6y9H7G0XcpHW/H+/VTKsj68XLjHrxUuJMk6yXIejptlWZeW8MrfPU+IUOeZpD8Gj3w0j+Yuy0MXpinBKff2p9J+vgtAcjtfBy/X1Wh0OW7G7MSi4kk045koCRNzOsi4Y1oNGJRYZIcu7RlewGi+C+Br0jIecv/ALihlu6YRIdUQt236xqAl4HNjayvPHHvvv+9hFfrdcdv341xGSaJPsSljWpFjRMDOiOAhbeZBuKxNYSKRfsrHl/r+Ei/6i28mCDx4CqwT+cV2UskTd8is9ZNOa5qFDNRDyfMTrjpenNfLHnCXECQd/2veYvM4WuIGcG4J8IUpU8xLQWZaw6YAQor/8VPN0u31udU//BAIS3kAyYkDdwZkVssswWJus6f0dpgyKtPGZLFUbPDX2VLAJMuCsCabss9MM+GsufW5AxD7rImFgCE8w0c5k0c2/5knS2MpgrpeU3y1qFNglJnJsWe2ofUE=
  on:
    tags: true
