from hudai.resources.article_highlights import ArticleHighlightsResource
from hudai.resources.article_key_term import ArticleKeyTermResource
from hudai.resources.article import ArticleResource
from hudai.resources.company_key_term import CompanyKeyTermResource
from hudai.resources.company import CompanyResource
from hudai.resources.domain import DomainResource
from hudai.resources.key_term import KeyTermResource
from hudai.resources.system_event import SystemEventResource
from hudai.resources.system_task import SystemTaskResource
from hudai.resources.text_corpus import TextCorpusResource
from hudai.resources.user_company import UserCompanyResource
from hudai.resources.user_key_term import UserKeyTermResource
from hudai.resources.user import UserResource
